// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA23GZF_a7_ufi5mSE2S1HeUCcFscCKgGA',
    appId: '1:1007120454910:android:4e5b24788bd897f5a6c1af',
    messagingSenderId: '1007120454910',
    projectId: 'projectpubg-e5215',
    storageBucket: 'projectpubg-e5215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_hgl3s6zf9k20Khy-p_I9hvYCdWNUCeU',
    appId: '1:1007120454910:ios:7389246373e4e3f9a6c1af',
    messagingSenderId: '1007120454910',
    projectId: 'projectpubg-e5215',
    storageBucket: 'projectpubg-e5215.firebasestorage.app',
    iosBundleId: 'com.jdj.ggcoach.ggCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_hgl3s6zf9k20Khy-p_I9hvYCdWNUCeU',
    appId: '1:1007120454910:ios:7389246373e4e3f9a6c1af',
    messagingSenderId: '1007120454910',
    projectId: 'projectpubg-e5215',
    storageBucket: 'projectpubg-e5215.firebasestorage.app',
    iosBundleId: 'com.jdj.ggcoach.ggCoach',
  );
}
